# Generated by Django 4.0 on 2022-01-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total_de_la_compra',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
